### ISSUE TITLE
计划增加国际化支持

### ISSUE THREAD

**Issue by zhuweiyou** [fpass/web#11]
使用 `vue-i18n` 模块，现在有两种选择

### 通过子域名区分

- 中文 - `//cn.fpass.ga`
- 英文 - ` //fpass.ga`

### 通过子目录区分

- 中文 - `//fpass.ga/cn`
- 英文 - ` //fpass.ga/`

先支持两种，默认英文

**Comment by zhuweiyou** [comment]
@huangdenghe 来点意见

**Comment by huangdenghe** [comment]
建议通过子目录区分，默认显示语言根据浏览器设置。域名区分的分式，我认为是部署在不同地区服务器的不同站点更适合采用

**Comment by zhuweiyou** [comment]
是用 cn 还是 zh-CN 比较好？

**Comment by huangdenghe** [comment]
我倾向于使用zh-CN这样的全称

**Comment by zhuweiyou** [comment]
已实现 https://github.com/fpass/fpass/pull/12
